services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

  backend:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://hariprasathg6380_db_user:Hari6380@cluster0.0ihyu5r.mongodb.net/maheswari_industries?retryWrites=true&w=majority&appName=Cluster0